# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  test:
    parameters:
      stack:
        type: string
      channel:
        type: string
    environment:
      STACK: << parameters.stack >>
      GOOGLE_CHROME_CHANNEL: << parameters.channel >>
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker:
          version: 20.10.11
      - checkout
      - run:
          name: "Running test"
          command: ./support/test.sh "${STACK}"

workflows:
  main:
    jobs:
      - test:
          matrix:
            parameters:
              channel: [stable, beta, unstable]
              stack: [heroku-18, heroku-20, heroku-22]
      - test: #default
          channel: ""
          stack: heroku-22
